dist: bionic
jobs:
  include:
  - name: pongo shell, LuaCov
    env: TEST_SCRIPT="assets/ci/pongo_shell.test.sh assets/ci/pongo_luacov.test.sh"
  - name: pongo build, pongo expose
    env: TEST_SCRIPT="assets/ci/pongo_build.test.sh assets/ci/pongo_expose.test.sh"
  - name: pongo run (CE releases)
    env: TEST_SCRIPT="assets/ci/pongo_run_ce.test.sh"
  - name: pongo run (EE releases)
    env: TEST_SCRIPT="assets/ci/pongo_run_ee.test.sh"
env:
  global:
  # for Enterprise images
  - PULP_USERNAME=admin
  - secure: cWRtevuFdESmsaWQ+NMY3z2gCpuuFrjvUiF7JU2qgJnPQhVt4o+VLyXi9RzZx5V6EMPScGtzwQH12rarABTbnd2ZKHgyFk+6r5WrbtRIbdsfBdd0QJaEqYTNYTMO4LVc6wy4/brcyOthHZCL5V/Gl8gAnhg/H9fEFeWi6XPUAEw4rONf0bRkPlOQiLYaEX7Uso6tS8AO9fAgYeS12RFgSaCC38BWiYcghts3ekjpchU07G09U2u1cmYn6kVcKjsCtjuTgDCZUdYLnURaxRZd0OWZrTu/F5xMS2Kef/cVpcCi9/pWZox+vOK6/RHyh5o85v0920BPtBVYp46jFa45O6cnnpe67UHTZQ0ripNm7BxaAvnwVtfvY/s54+KAN2R3dC03J2/CE9qaGe8f31B9TeLrcSIHu3ju8b4qquhS8dT5yj4Rf+38h48BVTweDri4iDt8iqPEzaCti+MPDOg2jXMBHDKckj0mK3VzKBAmdEjm/LxrWcs12CkhV6pM5tJS6+6STULaH7zAbCtJdjO0fBs9xHHe54B04phw/SUOFSBRgY9XD5Inm1Ibou6LMrmMSWztWVrIInB7urGKdH+CohEN83f1QQCQb8SNKi/iU1zevhvYTthB6IdLOX+rKT1HtN+rSe1Oy0Dc1YB0eyW0nG9z/nYIqSFzUVFLwN0UjAY=
  - DOCKER_USERNAME=kongcloudpull
  - secure: B9kfte5/t/cxcHiV+yOYu6daFtgmawDheQJrHo640OumM5bGXquU6WVgNczyhVojqdmOcL04FNqsGzWmSK2H0BjU6FFoXI6uvpEXvEH3IXwwRVVxzFFgna948KPSyKEK9YaVAAPuV2epy83BL+wv9lgMsdw7AzKiF9//XUIbGD5XeS1frG7o+FMBifvURrJ5ILQRoWNe8vQv1dQcRpSTWMjAsmPNVfW9YzfG6+HCWrobusFJo+tVgxy9+MYYJavZjFvnIludiFacjMhYf2d+JrLa+zOL5J6J40x32QUbo8JYWWlwFHumMnth1PunvmhPCGVOiCarNnPAclt9kSjBvtVJjzCv7syEICnsv1niw5y6v0WbyHrrtvzXMo4AUf2JJuftX0Y4jaJp1zeF9eVqRiGxuvE9gTnzorYaTKvopEbOPNSXLfdPTkMca8uFyXeyTs/6mdgPXC6Qo9hnqzbEGd1pZpIpicJ6Wk2aAAh4yomxUQLyl0N0JHuYiTOdk//3bYl4tCFpI3KmVpjKiuHRPUA1VCQHw8Hj3l5Sfdc+S/8y1sxu5bhwDSJXbZB3hlXOkCATTHQfAH81o4SoXRV5CCAMebRudB1v7deqzQY5+tkT/zFVoZjUz7n7GEjwQf/eWrRUEaVYk2uY7jySXA5/4ASEiBWDIngKtDMnDIqsfYU=
install:
- sudo apt-get install figlet
- make install
- export PATH=~/.local/bin/:$PATH
script:
- make lint
- assets/ci/run.sh --suite "Pongo test suite" $TEST_SCRIPT
