dist: focal

jobs:
  include:
  - name: pongo shell, LuaCov
    env: TEST_SCRIPT="assets/ci/pongo_shell.test.sh assets/ci/pongo_luacov.test.sh"
  - name: pongo build, pongo expose
    env: TEST_SCRIPT="assets/ci/pongo_build.test.sh assets/ci/pongo_expose.test.sh"
  - name: pongo run (CE releases)
    env: TEST_SCRIPT="assets/ci/pongo_run_ce.test.sh"
  - name: pongo run (EE releases)
    env: TEST_SCRIPT="assets/ci/pongo_run_ee.test.sh"
install:
- sudo apt-get install figlet
- make install
- export PATH=~/.local/bin/:$PATH
script:
- make lint
- assets/ci/run.sh --suite "Pongo test suite" $TEST_SCRIPT
