FROM kong-ee


# WARNING: spec/fixtures/ has some license related things?
# can we share that safely??


# copy required dev files
COPY bin                       /kong/bin
COPY spec/fixtures             /kong/spec/fixtures
COPY spec/helpers.lua          /kong/spec/helpers.lua
COPY spec/kong_tests.conf      /kong/spec/kong_tests.conf
COPY spec-ee/fixtures          /kong/spec-ee/fixtures
COPY spec-ee/helpers.lua       /kong/spec-ee/helpers.lua
COPY Makefile                  /kong/Makefile
